### PR TITLE
RCL 2&3 haulers will drop at spawn and not move around work parts

### PR DESCRIPTION
**Pull request by karlthepagan**
another respawn tweak, also adds the dropping action to in-room haulers

### CODE REVIEW

**Comment by karlthepagan** [comment]
this needs strategies or the creeps start cycling on the energy at their feet

**Comment by karlthepagan** [comment]
I really like the debounce API. I'm looking into this algorithm a little bit now.

**Comment by karlthepagan** [comment]
@chobobobo please let me know which debounce strategy is capable of resolving this in 0.7

without a proposal I will have to find a quick fix

**Comment by karlthepagan** [comment]
The alternative is that we must remove haulers from the default configuration until RCL3

**Comment by chobobobo** [comment]
If you want to debounce, you would need something similar to withdraw's assignDebounce that checks all available outflow energy uses before it assigns pickup.  I think we should also find some way to cache those checks otherwise we are checking all outflow actions twice.

**Pull request closed without merging**
