### PR TITLE
build extensions around spawn.

### PR DESCRIPTION
**Pull request by mikiones**
auto build extensions around spawn

### CODE REVIEW

**Comment by mikiones** [comment]
#17 kind of

**Comment by mikiones** [comment]
upgraders should not work until max of extensions are builded.
unless there is downgrade

**Comment by torin555** [comment]
Do you have this set up in a way it can be disabled?

**Comment by mikiones** [comment]
not atm.

**Comment by torin555** [comment]
Might be good to do that before the merge, this has the potential to break in bad ways.

**Comment by cyberblast** [comment]
I'm also unsure about it. I think we should do some evaluation with it and maybe further development. 
I will set up a new branch for it.

**Comment by mikiones** [comment]
rn is very simple build in predefined pattern if place is not taken. the RoomPosition extension is probably worth pulling into dev branch now. rest i still toying with

**Comment by cyberblast** [comment]
Can you create a new pull request for the new branch please

**Comment by mikiones** [comment]
sure give me sec

**Pull request closed without merging**
