### PR TITLE
[WIP] Refactor action.reallocating to be an outflow only action

### PR DESCRIPTION
**Pull request by chobobobo**
The idea is that reallocating should only handle deliveries of resources, ~a new action for forced unloading (creep.action.unloading) will handle structures that need to be unloaded (like labs that have changed resources).~ unloading will be handled by withdraw & uncharge

This will require modifying withdraw & uncharging to handle any kind of resource and moving unloadStructure functionality into them, and to debounce their use based on reallocating.findNeeding().  I also plan to add terminals and labs as valid structures for the withdrawing action, returning the nearest valid target for now, strategies can further specialize which structures a creep should get resources from.

Should containers be a part of reallocating, why are they currently?

### CODE REVIEW

**Comment by karlthepagan** [comment]
I started observing a cycle in dev, this might be a useful observation or not.

The current stuck cycle is withdrawing -> storing -> (debounce) -> reallocating (nothing to reallocate) -> withdrawing

**Comment by chobobobo** [comment]
The bug to look for there is why reallocating was assigned if there was nothing to reallocate​.

**Comment by karlthepagan** [comment]
How does this change relate to #1032 (WIP refactor reallocating)?

**Comment by chobobobo** [comment]
This is very much on-hold and not up to date with my current understanding of actions, which are expressed in #1032 I will rewrite this once 0.7.0 as branched as it's a big job, and there will be conflicts if I do it now.

**Pull request closed without merging**
